name: Build
on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          persist-credentials: false
          submodules: 'recursive'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install
        run: pnpm install
      # - name: Build and Analysis
      #   run: yarn build && yarn analysis
      - name: Build
        run: |
          pnpm build
          touch build/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        with:
          branch: gh-pages
          folder: dist
#   lint:
#     name: Lint
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '14'
#       - name: Checkout Repository
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: '0'
#           submodules: 'recursive'
#       - name: Cache yarn
#         uses: c-hive/gha-yarn-cache@v2
#       - name: Install
#         run: yarn install
#       - name: Lint
#         run: yarn lintci

# name: pnpm Example Workflow
# on:
#   push:
# jobs:
#   build:
#     runs-on: ubuntu-20.04
#     strategy:
#       matrix:
#         node-version: [15]
#     steps:
#       - uses: actions/checkout@v3
#       - uses: pnpm/action-setup@v2
#         with:
#           version: 7
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'pnpm'
#       - name: Install dependencies
#         run: pnpm install
